apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: colourmaps.colours.example.com
spec:
  group: colours.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object #must be object at the root
          properties:
            spec:
              type: object
              properties:
                colour:
                  type: object
                  additionalProperties:
                    type: string
                  x-kubernetes-map-type: atomic
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: colourmaps
    singular: colourmap
    kind: ColourMap
    shortNames:
    - cmap
